@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":RealodexParser" as RealodexParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "r:AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add n/John Doe a/6 College Ave West ..")
activate LogicManager

LogicManager -> RealodexParser : parseCommand("add n/John Doe a/6 College Ave West ..")
activate RealodexParser

create AddCommandParser
RealodexParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> RealodexParser
deactivate AddCommandParser

RealodexParser -> AddCommandParser : parse("add n/John Doe a/6 College Ave West ..")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : r
deactivate AddCommand

AddCommandParser --> RealodexParser : r
deactivate AddCommandParser

AddCommandParser -[hidden]-> RealodexParser
destroy AddCommandParser

RealodexParser --> LogicManager : r
deactivate RealodexParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : addPerson(Person)
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
