@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class FilterCommand {
  +COMMAND_WORD: String
  +MESSAGE_USAGE: String
  +MESSAGE_FILTER_HELP: String
  +execute(Model): CommandResult
}
Class CommandException

FilterCommand -up-|> Command
Command ..> CommandException: throws >
FilterCommand .right.> CommandException: throws >
@enduml
