@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Person
Class Address
Class Income
Class Email
Class Name
Class Phone
Class Family
Class Tag
Class HousingType
Class Remark
Class Birthday

Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Income
Person *--> "1" Email
Person *--> "1" Address
Person *--> "1" Family
Person *--> "1" HousingType
Person *--> "   1..2" Tag
Person *--> "   0..1" Remark
Person *--> "   0..1" Birthday

@enduml