@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":RealodexParser" as RealodexParser LOGIC_COLOR
participant ":HelpCommandParser" as HelpCommandParser LOGIC_COLOR
participant "h:HelpCommand" as HelpCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add help")
activate LogicManager

LogicManager -> RealodexParser : parseCommand("add help")
activate RealodexParser

create HelpCommandParser
RealodexParser -> HelpCommandParser
activate HelpCommandParser

HelpCommandParser --> RealodexParser
deactivate HelpCommandParser

RealodexParser -> HelpCommandParser : parse("add")
activate HelpCommandParser

create HelpCommand
HelpCommandParser -> HelpCommand
activate HelpCommand

HelpCommand --> HelpCommandParser :
deactivate HelpCommand

HelpCommandParser --> RealodexParser :
deactivate HelpCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
HelpCommandParser -[hidden]-> RealodexParser
destroy HelpCommandParser

RealodexParser --> LogicManager :
deactivate RealodexParser

[<--LogicManager
deactivate LogicManager
@enduml