@startuml
!include style.puml
skinparam ArrowFontStyle plain

box SortCommand MODEL_COLOR_T1
participant ":SortCommand" as SortCommand MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
participant ":Realodex" as Realodex MODEL_COLOR
participant ":ObservableList<Person>" as ObservableList MODEL_COLOR
end box



[-> SortCommand : execute(model)
activate SortCommand

SortCommand -> Model: getRealodex()
activate Model
Model -> SortCommand
deactivate Model

SortCommand -> Realodex : getCopyOfInternalListOfUniquePersonsList()
activate Realodex

Realodex --> SortCommand : list of persons
deactivate Realodex

SortCommand -> ObservableList : sort(new BirthdayComparator())
activate ObservableList

ObservableList -->  SortCommand:
deactivate ObservableList

SortCommand -> Realodex : setPersons(copiedInternalListForSorting)
activate Realodex

Realodex --> SortCommand :
deactivate Realodex

[<--SortCommand
deactivate SortCommand

@enduml
